# Generated by Django 3.1.7 on 2021-02-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('auth', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=300)),
            ],
        ),
    ]
